export const MOVIES_POPULAR_REQUEST = 'MOVIES_POPULAR_REQUEST' as const
export const MOVIES_POPULAR_SUCCESS = 'MOVIES_POPULAR_SUCCESS' as const
export const MOVIES_POPULAR_FAILURE = 'MOVIES_POPULAR_FAILURE' as const

export const INCREMENT_PAGE = 'INCREMENT_PAGE' as const
export const DECREMENT_PAGE = 'DECREMENT_PAGE' as const
