export const MOVIE_DETAILS_REQUEST = 'MOVIE_DETAILS_REQUEST' as const
export const MOVIE_DETAILS_SUCCESS = 'MOVIE_DETAILS_SUCCESS' as const
export const MOVIE_DETAILS_FAILURE = 'MOVIE_DETAILS_FAILURE' as const

export const MOVIE_VIDEO_REQUEST = 'MOVIE_VIDEO_REQUEST' as const
export const MOVIE_VIDEO_SUCCESS = 'MOVIE_VIDEO_SUCCESS' as const
export const MOVIE_VIDEO_FAILURE = 'MOVIE_VIDEO_FAILURE' as const

export const MOVIE_KEY_WORDS_REQUEST = 'MOVIE_KEY_WORDS_REQUEST' as const
export const MOVIE_KEY_WORDS_SUCCESS = 'MOVIE_KEY_WORDS_SUCCESS' as const
export const MOVIE_KEY_WORDS_FAILURE = 'MOVIE_KEY_WORDS_FAILURE' as const
